[repository]
name = "hymission"
authors = ["wilf"]

[hymission]
description = "Mission Control style overview plugin prototype for Hyprland"
authors = ["wilf"]
output = "build-cmake/libhymission.so"
build = [
  "cmake -E rm -f build-cmake/CMakeCache.txt",
  "cmake -DCMAKE_BUILD_TYPE=Release -B build-cmake",
  "cmake --build build-cmake -j $(nproc)",
  "install -Dm755 build-cmake/hymission-search-input \"$HOME/.local/bin/hymission-search-input\""
]
