[repository]
name = "hymission"
authors = ["wilf"]

[hymission]
description = "Mission Control style overview plugin prototype for Hyprland"
authors = ["wilf"]
output = "build-cmake/libhymission.so"
build = [
  "cmake -DCMAKE_BUILD_TYPE=Release -B build-cmake",
  "cmake --build build-cmake -j $(nproc)"
]
